[platformio]
default_envs = esp32dev
src_dir = firmware/src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  rfetick/MPU6050_light @ ^1.1.0
  adafruit/Adafruit PWM Servo Driver Library
  adafruit/Adafruit BusIO
  bblanchon/ArduinoJson
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
